name: Flask Base

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-18.04
   
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
        
    - name: Install dependencies
      run: pip install black flake8

    - name: Flake
      run: flake8 canonicalwebteam tests

    - name: Black
      run: black --line-length 79 --check canonicalwebteam tests
  
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config settings.virtualenvs.create false
        poetry install

    - name: Test
      run: python -m unittest discover tests

